version: '3.9'

services:
  db:
    build:
      context: ./
      dockerfile: Dockerfile
    image: custom-mysql
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    container_name: wp-db
    environment:
      MYSQL_ROOT_PASSWORD: genpass
      MYSQL_DATABASE: wpdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: genpass
    networks:
      - wp

  phpmyadmin:
    image: 10.100.100.21:5000/phpmyadmin
    links:
      - db:db
    ports:
      - "8001:80"
    container_name: wp-phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: genpass
      MYSQL_ROOT_PASSWORD: genpass
      UPLOAD_LIMIT: 100M
    networks:
      - wp

  wordpress:
    depends_on:
      - db
    image: 10.100.100.21:5000/wordpress
    ports:
      - "8000:80"
    container_name: wp-wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: genpass
      WORDPRESS_DB_NAME: wpdb
    volumes:
      - ./:/var/www/html
    networks:
      - wp

networks:
  wp:
    driver: bridge
    attachable: true