version: '3.9'

services:
  web:
    image: 10.100.100.21:5000/laravel
    ports:
      - "8001:80"

  database:
    image: 10.100.100.21:5000/mysql
    environment:
      MYSQL_ROOT_PASSWORD: genpass
    ports:
      - "127.0.0.1:3306:3306"

  phpmyadmin:
    image: 10.100.100.21:5000/phpmyadmin
    ports:
      - "8080:80"

  mailhog:
    image: 10.100.100.21:5000/mailhog
    ports:
      - "127.0.0.1:1025:1025"
      - "8025:8025"
