version: '3'

services:
  web:
    image: laravelfans/laravel
    ports:
      - "127.0.0.1:8001:80"

  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: genpass
    ports:
      - "127.0.0.1:3306:3306"

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "127.0.0.1:8080:80"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "127.0.0.1:1025:1025"
      - "127.0.0.1:8025:8025"
